<?php
/**
 * @file
 * Define a layout 2cols left bootstrap.
 */

$plugin = array(
  'title'    => "Layout 2Cols (sidebar left)",
  'category' => "Bootstrap",
  'icon'     => '2cols-sidebar-left.png',
  'theme'    => '2cols-sidebar-left',
  'css'      => '2cols-sidebar-left.css',
  'regions'  => array(
    'top'     => 'Top',
    'sidebar'  => 'Sidebar',
    'center'  => 'Center',
    'bottom'  => 'Bottom',
  ),
);
