<?php
/**
 * @file
 * Define a layout bricks bootstrap.
 */

$plugin = array(
  'title'    => "Layout Bricks",
  'category' => "Bootstrap",
  'icon'     => 'bricks.png',
  'theme'    => 'bricks',
  'css'      => 'bricks.css',
  'regions'  => array(
    'top'            => 'Top',
    'top-header'     => 'Top Header',
    'top-left'       => 'Top Left',
    'top-right'      => 'Top Right',
    'top-footer'     => 'Top Footer',
    'sidebar-top'    => 'Sidebar Top',
    'center'         => 'Center',
    'bottom-header'  => 'Bottom Header',
    'bottom-left'    => 'Bottom Left',
    'bottom-right'   => 'Bottom Right',
    'bottom-footer'  => 'Bottom Footer',
    'sidebar-bottom' => 'Sidebar Bottom',
    'bottom'         => 'Bottom',
  ),
);
